import 'dart:typed_data';

import 'package:flutter/material.dart';

import '../../../app_theme.dart';
import '../../../models/goat_model.dart';
import '../../../models/trading_purchase_model.dart';
import '../../../services/firestore_service.dart';
import '../../../services/goat_service.dart';
import '../../../services/image_service.dart';
import '../../../services/trading_service.dart';
import '../../../widgets/fast_route.dart';
import '../../../widgets/image_source_sheet.dart';
import '../../../widgets/photo_upload_circle.dart';
import 'registration_completed_screen.dart';

/// Tasks 2.2–2.4 — Single goat registration form, wired to
/// GoatService.registerGoat().
///
/// Goat ID is never entered here — it's generated by GoatService's
/// counter transaction at save time.
///
/// Loop behaviour (Tasks 2.4–2.6):
/// - "Save & Next": saves the goat, then either loads a blank form for
///   the next goat, or — once the purchase is fully registered —
///   replaces this screen with RegistrationCompletedScreen (Task 2.6).
/// - "Save & Continue Later": saves the goat, then returns straight to
///   Select Purchase, as Task 2.5 describes.
class GoatRegistrationFormScreen extends StatefulWidget {
  final String farmId;
  final TradingPurchase purchase;

  const GoatRegistrationFormScreen({
    super.key,
    required this.farmId,
    required this.purchase,
  });

  @override
  State<GoatRegistrationFormScreen> createState() =>
      _GoatRegistrationFormScreenState();
}

class _GoatRegistrationFormScreenState
    extends State<GoatRegistrationFormScreen> {
  final _formKey = GlobalKey<FormState>();

  final _breedController = TextEditingController();
  final _ageController = TextEditingController();
  final _weightController = TextEditingController();
  final _colorController = TextEditingController();
  final _notesController = TextEditingController();

  String _healthStatus = Goat.healthStatusValues.first;

  Uint8List? _photoBytes;
  String? _photoContentType;

  bool _saving = false;

  /// Task 2.3 — updated after every successful save so the progress
  /// header reflects registeredCount/totalGoats without a separate
  /// field, as the plan specifies.
  late TradingPurchase _purchase;

  @override
  void initState() {
    super.initState();
    _purchase = widget.purchase;
  }

  @override
  void dispose() {
    _breedController.dispose();
    _ageController.dispose();
    _weightController.dispose();
    _colorController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  void _showSnack(String message, {bool isError = false}) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: isError ? AppColors.error : AppColors.darkGreen,
      ),
    );
  }

  Future<void> _pickPhoto() async {
    try {
      final picked = await showImageSourceSheet(context, isGoatPhoto: true);
      if (picked == null) return;
      setState(() {
        _photoBytes = picked.bytes;
        _photoContentType = picked.contentType;
      });
    } on ImageTooLargeException catch (e) {
      _showSnack(e.message, isError: true);
    } catch (_) {
      _showSnack('Could not add photo. Please try again.', isError: true);
    }
  }

  void _clearFormForNextGoat() {
    _breedController.clear();
    _ageController.clear();
    _weightController.clear();
    _colorController.clear();
    _notesController.clear();
    setState(() {
      _healthStatus = Goat.healthStatusValues.first;
      _photoBytes = null;
      _photoContentType = null;
    });
  }

  // ===========================================================================
  // SAVE (Task 2.4)
  // ===========================================================================

  /// Runs the save itself — shared by both buttons. Returns the updated
  /// purchase (re-read after the transaction) on success, or null if
  /// validation failed or the save errored (a snackbar is already shown
  /// in that case).
  Future<TradingPurchase?> _saveGoat() async {
    if (!_formKey.currentState!.validate()) return null;

    final weight = double.tryParse(_weightController.text.trim()) ?? 0;

    setState(() => _saving = true);

    try {
      await GoatService.instance.registerGoat(
        farmId: widget.farmId,
        purchase: _purchase,
        breed: _breedController.text,
        age: _ageController.text,
        weight: weight,
        color: _colorController.text,
        healthStatus: _healthStatus,
        notes: _notesController.text,
        photo: _photoBytes,
        photoContentType: _photoContentType,
      );

      final updated = await TradingService.instance.getPurchase(
        widget.farmId,
        _purchase.id,
      );

      return updated ?? _purchase;
    } catch (e) {
      _showSnack(FirestoreService.instance.describeError(e), isError: true);
      return null;
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  Future<void> _saveAndNext() async {
    final updated = await _saveGoat();
    if (updated == null || !mounted) return;

    if (updated.pendingCount <= 0) {
      // Purchase fully registered — hand off to the completion screen
      // (Task 2.6). pushReplacement so the (now-finished) form can't be
      // reached again via back button.
      Navigator.of(context).pushReplacement(
        fastRoute(
          RegistrationCompletedScreen(
            farmId: widget.farmId,
            purchase: updated,
          ),
        ),
      );
      return;
    }

    setState(() => _purchase = updated);
    _clearFormForNextGoat();
    _showSnack('Goat registered — ${updated.registeredCount}/${updated.totalGoats} done.');
  }

  Future<void> _saveAndContinueLater() async {
    final updated = await _saveGoat();
    if (updated == null || !mounted) return;

    _showSnack(
      'Saved. ${updated.registeredCount}/${updated.totalGoats} registered so far.',
    );
    Navigator.of(context).pop();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.paleGreen,
      appBar: AppBar(
        backgroundColor: AppColors.paleGreen,
        elevation: 0,
        foregroundColor: AppColors.textDark,
        title: Text('Register Goat', style: AppTheme.heading(size: 17)),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _progressHeader(),
              const SizedBox(height: 22),
              Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Center(
                      child: PhotoUploadCircle(
                        imageBytes: _photoBytes,
                        label: 'Goat Photo (Optional)',
                        onTap: _pickPhoto,
                      ),
                    ),
                    const SizedBox(height: 22),
                    _label('Breed'),
                    _textField(
                      _breedController,
                      hint: 'e.g. Sojat, Jamnapari',
                    ),
                    const SizedBox(height: 16),
                    Row(
                      children: [
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              _label('Age'),
                              _textField(
                                _ageController,
                                hint: 'e.g. 8-10 months',
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              _label('Weight (kg)'),
                              _textField(
                                _weightController,
                                hint: 'e.g. 22',
                                keyboardType: const TextInputType.numberWithOptions(
                                  decimal: true,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 16),
                    _label('Color'),
                    _textField(
                      _colorController,
                      hint: 'e.g. Brown & White',
                    ),
                    const SizedBox(height: 16),
                    _label('Health Status'),
                    _dropdown(
                      _healthStatus,
                      Goat.healthStatusValues,
                          (v) => setState(() => _healthStatus = v),
                    ),
                    const SizedBox(height: 16),
                    _label('Notes'),
                    _textField(
                      _notesController,
                      hint: 'Optional notes',
                      maxLines: 3,
                      optional: true,
                    ),
                    const SizedBox(height: 28),
                    Row(
                      children: [
                        Expanded(
                          child: OutlinedButton(
                            onPressed: _saving ? null : _saveAndContinueLater,
                            style: OutlinedButton.styleFrom(
                              foregroundColor: AppColors.primaryGreen,
                              side: const BorderSide(
                                color: AppColors.primaryGreen,
                              ),
                              padding: const EdgeInsets.symmetric(
                                vertical: 15,
                              ),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                            child: const Text(
                              'Save & Continue Later',
                              textAlign: TextAlign.center,
                              style: TextStyle(fontWeight: FontWeight.w700),
                            ),
                          ),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: ElevatedButton(
                            onPressed: _saving ? null : _saveAndNext,
                            style: ElevatedButton.styleFrom(
                              backgroundColor: AppColors.primaryGreen,
                              foregroundColor: Colors.white,
                              elevation: 0,
                              padding: const EdgeInsets.symmetric(
                                vertical: 15,
                              ),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                            child: _saving
                                ? const SizedBox(
                              height: 18,
                              width: 18,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                                color: Colors.white,
                              ),
                            )
                                : const Text(
                              'Save & Next',
                              style: TextStyle(fontWeight: FontWeight.w700),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  // ===========================================================================
  // PROGRESS HEADER (Task 2.3)
  // ===========================================================================

  Widget _progressHeader() {
    final total = _purchase.totalGoats;
    final registered = _purchase.registeredCount;
    final percent = total > 0 ? ((registered / total) * 100).round() : 0;

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: AppColors.tradingBlue.withOpacity(0.08),
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: AppColors.tradingBlue.withOpacity(0.20)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(
                Icons.shopping_cart_outlined,
                color: AppColors.tradingBlue,
                size: 20,
              ),
              const SizedBox(width: 10),
              Expanded(
                child: Text(
                  '${_purchase.id} — ${_purchase.sellerName}',
                  style: AppTheme.body(size: 12, color: AppColors.textDark),
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          ClipRRect(
            borderRadius: BorderRadius.circular(6),
            child: LinearProgressIndicator(
              value: total > 0 ? registered / total : 0,
              minHeight: 8,
              backgroundColor: AppColors.tradingBlue.withOpacity(0.15),
              valueColor: const AlwaysStoppedAnimation(AppColors.tradingBlue),
            ),
          ),
          const SizedBox(height: 8),
          Text(
            '$registered of $total Registered — $percent%',
            style: AppTheme.heading(size: 13, color: AppColors.tradingBlue),
          ),
        ],
      ),
    );
  }

  Widget _label(String text) => Padding(
    padding: const EdgeInsets.only(bottom: 6),
    child: Text(text, style: AppTheme.heading(size: 13)),
  );

  Widget _dropdown(
      String value,
      List<String> options,
      ValueChanged<String> onChanged,
      ) {
    return Container(
      decoration: AppTheme.card(radius: 12),
      padding: const EdgeInsets.symmetric(horizontal: 12),
      child: DropdownButtonHideUnderline(
        child: DropdownButton<String>(
          value: value,
          isExpanded: true,
          items: options
              .map(
                (o) => DropdownMenuItem(
              value: o,
              child: Text(
                o,
                style: AppTheme.body(size: 13, color: AppColors.textDark),
              ),
            ),
          )
              .toList(),
          onChanged: (v) => onChanged(v ?? value),
        ),
      ),
    );
  }

  Widget _textField(
      TextEditingController controller, {
        String? hint,
        TextInputType? keyboardType,
        int maxLines = 1,
        bool optional = false,
      }) {
    return Container(
      decoration: AppTheme.card(radius: 12),
      child: TextFormField(
        controller: controller,
        keyboardType: keyboardType,
        maxLines: maxLines,
        validator: (v) =>
        (!optional && (v == null || v.trim().isEmpty)) ? 'Required' : null,
        decoration: InputDecoration(
          hintText: hint,
          hintStyle: AppTheme.body(size: 12),
          border: InputBorder.none,
          contentPadding: const EdgeInsets.all(14),
        ),
        style: AppTheme.body(size: 13, color: AppColors.textDark),
      ),
    );
  }
}