import 'dart:typed_data';

import 'package:flutter/material.dart';

import '../../../app_theme.dart';
import '../../../models/goat_model.dart';
import '../../../models/trading_purchase_model.dart';
import '../../../services/image_service.dart';
import '../../../widgets/image_source_sheet.dart';
import '../../../widgets/photo_upload_circle.dart';

/// Task 2.2 — Single goat registration form.
///
/// Fields: Goat Photo (optional), Breed, Age, Weight, Color, Health
/// Status, Notes. Goat ID is never entered here — it's generated by
/// GoatService's counter transaction at save time (Task 2.4).
///
/// This screen is UI-only for now. "Save & Next" / "Save & Continue
/// Later" are wired up to GoatService.registerGoat() and the
/// progress-loop behaviour (Tasks 2.3–2.5) in the next task — for now
/// they're placeholders so the form itself can be reviewed and run.
class GoatRegistrationFormScreen extends StatefulWidget {
  final String farmId;
  final TradingPurchase purchase;

  const GoatRegistrationFormScreen({
    super.key,
    required this.farmId,
    required this.purchase,
  });

  @override
  State<GoatRegistrationFormScreen> createState() =>
      _GoatRegistrationFormScreenState();
}

class _GoatRegistrationFormScreenState
    extends State<GoatRegistrationFormScreen> {
  final _formKey = GlobalKey<FormState>();

  final _breedController = TextEditingController();
  final _ageController = TextEditingController();
  final _weightController = TextEditingController();
  final _colorController = TextEditingController();
  final _notesController = TextEditingController();

  String _healthStatus = Goat.healthStatusValues.first;

  Uint8List? _photoBytes;
  String? _photoContentType;

  bool _saving = false;

  @override
  void dispose() {
    _breedController.dispose();
    _ageController.dispose();
    _weightController.dispose();
    _colorController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  void _showSnack(String message, {bool isError = false}) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: isError ? AppColors.error : AppColors.darkGreen,
      ),
    );
  }

  Future<void> _pickPhoto() async {
    try {
      final picked = await showImageSourceSheet(context, isGoatPhoto: true);
      if (picked == null) return;
      setState(() {
        _photoBytes = picked.bytes;
        _photoContentType = picked.contentType;
      });
    } on ImageTooLargeException catch (e) {
      _showSnack(e.message, isError: true);
    } catch (_) {
      _showSnack('Could not add photo. Please try again.', isError: true);
    }
  }

  // ===========================================================================
  // SAVE (placeholder — wired to GoatService.registerGoat in Task 2.4)
  // ===========================================================================

  Future<void> _saveAndNext() async {
    if (!_formKey.currentState!.validate()) return;
    _showSnack('Save & Next — coming in the next task.');
  }

  Future<void> _saveAndContinueLater() async {
    if (!_formKey.currentState!.validate()) return;
    _showSnack('Save & Continue Later — coming in the next task.');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.paleGreen,
      appBar: AppBar(
        backgroundColor: AppColors.paleGreen,
        elevation: 0,
        foregroundColor: AppColors.textDark,
        title: Text('Register Goat', style: AppTheme.heading(size: 17)),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _purchaseBanner(),
              const SizedBox(height: 22),
              Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Center(
                      child: PhotoUploadCircle(
                        imageBytes: _photoBytes,
                        label: 'Goat Photo (Optional)',
                        onTap: _pickPhoto,
                      ),
                    ),
                    const SizedBox(height: 22),
                    _label('Breed'),
                    _textField(
                      _breedController,
                      hint: 'e.g. Sojat, Jamnapari',
                    ),
                    const SizedBox(height: 16),
                    Row(
                      children: [
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              _label('Age'),
                              _textField(
                                _ageController,
                                hint: 'e.g. 8-10 months',
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              _label('Weight (kg)'),
                              _textField(
                                _weightController,
                                hint: 'e.g. 22',
                                keyboardType: const TextInputType.numberWithOptions(
                                  decimal: true,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 16),
                    _label('Color'),
                    _textField(
                      _colorController,
                      hint: 'e.g. Brown & White',
                    ),
                    const SizedBox(height: 16),
                    _label('Health Status'),
                    _dropdown(
                      _healthStatus,
                      Goat.healthStatusValues,
                          (v) => setState(() => _healthStatus = v),
                    ),
                    const SizedBox(height: 16),
                    _label('Notes'),
                    _textField(
                      _notesController,
                      hint: 'Optional notes',
                      maxLines: 3,
                      optional: true,
                    ),
                    const SizedBox(height: 28),
                    Row(
                      children: [
                        Expanded(
                          child: OutlinedButton(
                            onPressed: _saving ? null : _saveAndContinueLater,
                            style: OutlinedButton.styleFrom(
                              foregroundColor: AppColors.primaryGreen,
                              side: const BorderSide(
                                color: AppColors.primaryGreen,
                              ),
                              padding: const EdgeInsets.symmetric(
                                vertical: 15,
                              ),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                            child: const Text(
                              'Save & Continue Later',
                              textAlign: TextAlign.center,
                              style: TextStyle(fontWeight: FontWeight.w700),
                            ),
                          ),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: ElevatedButton(
                            onPressed: _saving ? null : _saveAndNext,
                            style: ElevatedButton.styleFrom(
                              backgroundColor: AppColors.primaryGreen,
                              foregroundColor: Colors.white,
                              elevation: 0,
                              padding: const EdgeInsets.symmetric(
                                vertical: 15,
                              ),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                            child: _saving
                                ? const SizedBox(
                              height: 18,
                              width: 18,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                                color: Colors.white,
                              ),
                            )
                                : const Text(
                              'Save & Next',
                              style: TextStyle(fontWeight: FontWeight.w700),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _purchaseBanner() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: AppColors.tradingBlue.withOpacity(0.08),
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: AppColors.tradingBlue.withOpacity(0.20)),
      ),
      child: Row(
        children: [
          const Icon(
            Icons.shopping_cart_outlined,
            color: AppColors.tradingBlue,
            size: 20,
          ),
          const SizedBox(width: 10),
          Expanded(
            child: Text(
              'Registering for ${widget.purchase.id} — ${widget.purchase.sellerName}',
              style: AppTheme.body(size: 12, color: AppColors.textDark),
            ),
          ),
        ],
      ),
    );
  }

  Widget _label(String text) => Padding(
    padding: const EdgeInsets.only(bottom: 6),
    child: Text(text, style: AppTheme.heading(size: 13)),
  );

  Widget _dropdown(
      String value,
      List<String> options,
      ValueChanged<String> onChanged,
      ) {
    return Container(
      decoration: AppTheme.card(radius: 12),
      padding: const EdgeInsets.symmetric(horizontal: 12),
      child: DropdownButtonHideUnderline(
        child: DropdownButton<String>(
          value: value,
          isExpanded: true,
          items: options
              .map(
                (o) => DropdownMenuItem(
              value: o,
              child: Text(
                o,
                style: AppTheme.body(size: 13, color: AppColors.textDark),
              ),
            ),
          )
              .toList(),
          onChanged: (v) => onChanged(v ?? value),
        ),
      ),
    );
  }

  Widget _textField(
      TextEditingController controller, {
        String? hint,
        TextInputType? keyboardType,
        int maxLines = 1,
        bool optional = false,
      }) {
    return Container(
      decoration: AppTheme.card(radius: 12),
      child: TextFormField(
        controller: controller,
        keyboardType: keyboardType,
        maxLines: maxLines,
        validator: (v) =>
        (!optional && (v == null || v.trim().isEmpty)) ? 'Required' : null,
        decoration: InputDecoration(
          hintText: hint,
          hintStyle: AppTheme.body(size: 12),
          border: InputBorder.none,
          contentPadding: const EdgeInsets.all(14),
        ),
        style: AppTheme.body(size: 13, color: AppColors.textDark),
      ),
    );
  }
}