import 'package:cloud_firestore/cloud_firestore.dart';

/// One goat's line in the goat-wise Palai breakdown of a [MonthlyBill].
///
/// This is a snapshot taken at the moment the bill was generated — the
/// amount is whatever the owner typed for that goat that month (it may
/// differ from the goat's registered [PalaiGoat.pricing] if the owner
/// overrode it), so it should never be recalculated later from the
/// goat's current price.
class GoatBillingLine {
  final String goatId;

  /// Display label for the goat (name, or its code/tag if unnamed).
  final String label;

  /// The Palai amount entered for this goat for this specific bill.
  final double palaiAmount;

  const GoatBillingLine({
    required this.goatId,
    required this.label,
    required this.palaiAmount,
  });

  factory GoatBillingLine.fromMap(Map<String, dynamic> map) {
    return GoatBillingLine(
      goatId: map['goatId']?.toString() ?? '',
      label: map['label']?.toString() ?? '',
      palaiAmount: (map['palaiAmount'] as num?)?.toDouble() ?? 0,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'goatId': goatId,
      'label': label,
      'palaiAmount': palaiAmount,
    };
  }
}

/// Payment status of a monthly customer bill.
///
/// The UI may show:
/// - Unpaid
/// - Partially Paid
/// - Paid
///
/// The database stores the lowercase values defined here.
enum MonthlyBillStatus {
  unpaid,
  partial,
  paid,
}

/// A monthly bill generated for a Palai customer.
///
/// IMPORTANT:
/// This is different from the Final Bill generated during goat checkout.
///
/// Monthly Bill:
///   Customer-level recurring billing.
///
/// Final Bill:
///   Final financial settlement when a goat/goats are checked out.
///
/// A monthly bill is a snapshot. Once generated, the amounts used to
/// calculate that bill should not silently change because the customer's
/// current outstanding balance changes later.
class MonthlyBill {
  final String id;

  final String customerId;
  final String customerName;

  /// Human-readable bill number.
  ///
  /// Example:
  /// MB-2026-08-0001
  final String billNumber;

  /// First day of the billing month.
  ///
  /// Example:
  /// 2026-08-01
  final DateTime billingMonth;

  /// Last day of the billing month.
  final DateTime periodEnd;

  /// Number of active/boarded goats used when the bill was generated.
  final int goatCount;

  /// Monthly Palai charges before other adjustments.
  final double palaiCharges;

  /// Additional charges included in this monthly bill.
  final double otherCharges;

  /// Discount applied to this monthly bill.
  final double discount;

  /// Amount already outstanding before this bill was generated.
  ///
  /// This is a snapshot and should never be recalculated later.
  final double previousOutstanding;

  /// Net amount generated by this month's bill.
  ///
  /// Formula:
  ///
  /// palaiCharges + otherCharges - discount
  final double currentBillAmount;

  /// Amount of the customer's existing advance balance that was used to
  /// offset this bill, if any.
  ///
  /// This is a snapshot taken when the bill was generated and should never
  /// be recalculated later.
  final double advanceApplied;

  /// Total amount due after adding this bill to the previous outstanding
  /// and subtracting any advance that was applied.
  ///
  /// Formula:
  ///
  /// previousOutstanding + currentBillAmount - advanceApplied
  final double totalDue;

  /// Amount paid against THIS monthly bill.
  ///
  /// This may be less than [currentBillAmount] if the customer makes a
  /// partial payment.
  final double amountPaid;

  /// Amount still outstanding from this bill.
  final double remainingAmount;

  final MonthlyBillStatus status;

  final DateTime generatedAt;

  /// Set when the bill becomes completely paid.
  final DateTime? paidAt;

  /// Optional notes attached to this bill.
  final String notes;

  /// Optional snapshot of the farm name shown on the PDF.
  final String farmName;

  /// Optional snapshot of the farm address shown on the PDF.
  final String farmAddress;

  /// Optional snapshot of the farm phone shown on the PDF.
  final String farmPhone;

  /// Optional snapshot of the farm email shown on the PDF.
  final String farmEmail;

  /// Goat-wise Palai breakdown for this bill (one line per goat included
  /// in the current-month calculation). Empty for older bills generated
  /// before this breakdown existed, or for bills that don't have a
  /// goat-wise split (e.g. a purely manual outstanding entry).
  ///
  /// This is a snapshot — like every other amount on a MonthlyBill, it
  /// should never be recalculated from a goat's current price.
  final List<GoatBillingLine> goatBreakdown;

  const MonthlyBill({
    required this.id,
    required this.customerId,
    required this.customerName,
    required this.billNumber,
    required this.billingMonth,
    required this.periodEnd,
    required this.goatCount,
    required this.palaiCharges,
    required this.otherCharges,
    required this.discount,
    required this.previousOutstanding,
    required this.currentBillAmount,
    this.advanceApplied = 0,
    required this.totalDue,
    required this.amountPaid,
    required this.remainingAmount,
    required this.status,
    required this.generatedAt,
    this.paidAt,
    this.notes = '',
    this.farmName = '',
    this.farmAddress = '',
    this.farmPhone = '',
    this.farmEmail = '',
    this.goatBreakdown = const [],
  });

  // ================================================================
  // STATUS HELPERS
  // ================================================================

  static MonthlyBillStatus statusFromString(String? value) {
    switch (value) {
      case 'paid':
        return MonthlyBillStatus.paid;

      case 'partial':
      case 'partiallyPaid':
      case 'partially_paid':
        return MonthlyBillStatus.partial;

      case 'unpaid':
      default:
        return MonthlyBillStatus.unpaid;
    }
  }

  static String statusToString(MonthlyBillStatus status) {
    switch (status) {
      case MonthlyBillStatus.paid:
        return 'paid';

      case MonthlyBillStatus.partial:
        return 'partial';

      case MonthlyBillStatus.unpaid:
        return 'unpaid';
    }
  }

  String get statusLabel {
    switch (status) {
      case MonthlyBillStatus.paid:
        return 'PAID';

      case MonthlyBillStatus.partial:
        return 'PARTIALLY PAID';

      case MonthlyBillStatus.unpaid:
        return 'UNPAID';
    }
  }

  bool get isPaid => status == MonthlyBillStatus.paid;

  bool get isPartiallyPaid => status == MonthlyBillStatus.partial;

  bool get isUnpaid => status == MonthlyBillStatus.unpaid;

  // ================================================================
  // MONTH HELPERS
  // ================================================================

  int get month => billingMonth.month;

  int get year => billingMonth.year;

  String get monthYear {
    const months = <String>[
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];

    return '${months[billingMonth.month - 1]} ${billingMonth.year}';
  }

  /// Stable identifier used to prevent duplicate bills for the same
  /// customer/month/year.
  String get billingPeriodKey {
    final monthString = billingMonth.month.toString().padLeft(2, '0');

    return '${billingMonth.year}-$monthString';
  }

  /// Customer + billing period is the logical unique key.
  String get uniqueBillKey => '$customerId-$billingPeriodKey';

  // ================================================================
  // FIRESTORE
  // ================================================================

  factory MonthlyBill.fromDoc(
      DocumentSnapshot<Map<String, dynamic>> doc,
      ) {
    final data = doc.data() ?? {};

    final billingMonthValue = data['billingMonth'];
    final periodEndValue = data['periodEnd'];
    final generatedAtValue = data['generatedAt'];
    final paidAtValue = data['paidAt'];

    DateTime parseDate(
        dynamic value, {
          required DateTime fallback,
        }) {
      if (value is Timestamp) {
        return value.toDate();
      }

      if (value is DateTime) {
        return value;
      }

      return fallback;
    }

    return MonthlyBill(
      id: doc.id,

      customerId:
      data['customerId']?.toString() ?? '',

      customerName:
      data['customerName']?.toString() ?? '',

      billNumber:
      data['billNumber']?.toString() ?? doc.id,

      billingMonth: parseDate(
        billingMonthValue,
        fallback: DateTime.now(),
      ),

      periodEnd: parseDate(
        periodEndValue,
        fallback: DateTime.now(),
      ),

      goatCount:
      (data['goatCount'] as num?)?.toInt() ?? 0,

      palaiCharges:
      (data['palaiCharges'] as num?)?.toDouble() ?? 0,

      otherCharges:
      (data['otherCharges'] as num?)?.toDouble() ?? 0,

      discount:
      (data['discount'] as num?)?.toDouble() ?? 0,

      previousOutstanding:
      (data['previousOutstanding'] as num?)?.toDouble() ?? 0,

      currentBillAmount:
      (data['currentBillAmount'] as num?)?.toDouble() ?? 0,

      advanceApplied:
      (data['advanceApplied'] as num?)?.toDouble() ?? 0,

      totalDue:
      (data['totalDue'] as num?)?.toDouble() ?? 0,

      amountPaid:
      (data['amountPaid'] as num?)?.toDouble() ?? 0,

      remainingAmount:
      (data['remainingAmount'] as num?)?.toDouble() ?? 0,

      status: statusFromString(
        data['status']?.toString(),
      ),

      generatedAt: parseDate(
        generatedAtValue,
        fallback: DateTime.now(),
      ),

      paidAt: paidAtValue == null
          ? null
          : parseDate(
        paidAtValue,
        fallback: DateTime.now(),
      ),

      notes:
      data['notes']?.toString() ?? '',

      farmName:
      data['farmName']?.toString() ?? '',

      farmAddress:
      data['farmAddress']?.toString() ?? '',

      farmPhone:
      data['farmPhone']?.toString() ?? '',

      farmEmail:
      data['farmEmail']?.toString() ?? '',

      goatBreakdown: (data['goatBreakdown'] as List<dynamic>?)
          ?.map((e) => GoatBillingLine.fromMap(
        Map<String, dynamic>.from(e as Map),
      ))
          .toList() ??
          const [],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'customerId': customerId,
      'customerName': customerName,

      'billNumber': billNumber,

      'billingMonth':
      Timestamp.fromDate(billingMonth),

      'periodEnd':
      Timestamp.fromDate(periodEnd),

      'billingPeriodKey':
      billingPeriodKey,

      'goatCount': goatCount,

      'palaiCharges': palaiCharges,
      'otherCharges': otherCharges,
      'discount': discount,

      'previousOutstanding':
      previousOutstanding,

      'currentBillAmount':
      currentBillAmount,

      'advanceApplied':
      advanceApplied,

      'totalDue':
      totalDue,

      'amountPaid':
      amountPaid,

      'remainingAmount':
      remainingAmount,

      'status':
      statusToString(status),

      'generatedAt':
      Timestamp.fromDate(generatedAt),

      'paidAt': paidAt == null
          ? null
          : Timestamp.fromDate(paidAt!),

      'notes': notes,

      // ------------------------------------------------------------
      // Farm snapshot for historical PDFs.
      // ------------------------------------------------------------

      'farmName': farmName,
      'farmAddress': farmAddress,
      'farmPhone': farmPhone,
      'farmEmail': farmEmail,

      'goatBreakdown': goatBreakdown.map((g) => g.toMap()).toList(),
    };
  }

  // ================================================================
  // COPY
  // ================================================================

  MonthlyBill copyWith({
    String? id,
    String? customerId,
    String? customerName,
    String? billNumber,
    DateTime? billingMonth,
    DateTime? periodEnd,
    int? goatCount,
    double? palaiCharges,
    double? otherCharges,
    double? discount,
    double? previousOutstanding,
    double? currentBillAmount,
    double? advanceApplied,
    double? totalDue,
    double? amountPaid,
    double? remainingAmount,
    MonthlyBillStatus? status,
    DateTime? generatedAt,
    DateTime? paidAt,
    String? notes,
    String? farmName,
    String? farmAddress,
    String? farmPhone,
    String? farmEmail,
    List<GoatBillingLine>? goatBreakdown,
  }) {
    return MonthlyBill(
      id: id ?? this.id,
      customerId: customerId ?? this.customerId,
      customerName: customerName ?? this.customerName,
      billNumber: billNumber ?? this.billNumber,
      billingMonth: billingMonth ?? this.billingMonth,
      periodEnd: periodEnd ?? this.periodEnd,
      goatCount: goatCount ?? this.goatCount,
      palaiCharges: palaiCharges ?? this.palaiCharges,
      otherCharges: otherCharges ?? this.otherCharges,
      discount: discount ?? this.discount,
      previousOutstanding:
      previousOutstanding ?? this.previousOutstanding,
      currentBillAmount:
      currentBillAmount ?? this.currentBillAmount,
      advanceApplied: advanceApplied ?? this.advanceApplied,
      totalDue: totalDue ?? this.totalDue,
      amountPaid: amountPaid ?? this.amountPaid,
      remainingAmount:
      remainingAmount ?? this.remainingAmount,
      status: status ?? this.status,
      generatedAt: generatedAt ?? this.generatedAt,
      paidAt: paidAt ?? this.paidAt,
      notes: notes ?? this.notes,
      farmName: farmName ?? this.farmName,
      farmAddress: farmAddress ?? this.farmAddress,
      farmPhone: farmPhone ?? this.farmPhone,
      farmEmail: farmEmail ?? this.farmEmail,
      goatBreakdown: goatBreakdown ?? this.goatBreakdown,
    );
  }

  @override
  String toString() {
    return 'MonthlyBill('
        'id: $id, '
        'customer: $customerName, '
        'period: $monthYear, '
        'amount: $currentBillAmount, '
        'paid: $amountPaid, '
        'remaining: $remainingAmount, '
        'status: ${statusToString(status)}'
        ')';
  }
}